### ISSUE TITLE
tshark outputting nothing

### ISSUE THREAD

**Issue by HoangPhantom** [termux/termux-root-packages#108] opened 2019-07-09 07:26 UTC
Hello, when I'm trying to scan my network to do some penetration testing via tshark, it doesn't work. It outputs nothing and just gives me back my shell. It doesn't give me the help message either. I hope you can help fix this. Thank you.
Oh and this is my termux-info:
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/xeffyr/x11-packages-21 x11/main
https://dl.bintray.com/xeffyr/unstable-packages-21 unstable/main
https://dl.bintray.com/grimler/science-packages-21 science/stable
https://dl.bintray.com/grimler/termux-root-packages-21 root/stable
https://dl.bintray.com/grimler/game-packages-21 games/stable
https://termux.net stable/main
https://termux.net stable/main
System information:
Linux localhost 3.10.72 #1 SMP PREEMPT Tue Feb 16 18:23:49 CST 2016 armv7l Android
Termux-packages arch:
arm
Android version:
5.1
Device manufacturer:
Lenovo
Device model:
Lenovo TB3-710I
![20190709_141910](https://user-images.githubusercontent.com/46418295/60867533-48deed80-a255-11e9-9f9e-a3f80446d6bd.png)

**Comment by HoangPhantom** [comment] 2019-07-09 10:39
Gdb presented this:
warning: .dynamic section for "/system/lib/libpcre.so" is not at the expected address (wrong library or version mismatch?)

**Comment by Grimler91** [comment] 2019-07-12 12:02
@HoangPhantom in #95 you said that you "restarted termux" and it started working again, does the same not work now?

What's the exit code from tshark? (`tshark; echo $?`)

I can't reproduce this issue (I don't have an android 5 or 6 device) and it might even be an issue that only happens on your ROM. gdb doesn't output anything so there's also not much to go on to debug it.

Does the [android log](https://android.stackexchange.com/questions/14430/how-can-i-view-and-examine-the-android-log) say anything that seems to be relevant?

**Comment by HoangPhantom** [comment] 2019-07-12 12:31
I restarted at #95 and it works finely while but doesn't now.
Gdb's output:
![20190712_192615](https://user-images.githubusercontent.com/46418295/61128002-029ac000-a4db-11e9-8d0c-63192d7042a7.png)

Device log doesn't say much(Do I have to wait?):
![20190712_192924](https://user-images.githubusercontent.com/46418295/61128266-a1bfb780-a4db-11e9-85ed-844cd3a875d0.png)

**Comment by Grimler91** [comment] 2019-07-16 07:45
Closing since it tshark seem to work for you again: https://github.com/termux/termux-packages/issues/4059

**Closed by Grimler91** 2019-07-16 07:45 UTC
Labels: android-5
